### ISSUE TITLE
debug=True in api.py

### ISSUE THREAD

**Issue by TawfikYasser** [ramblingjordan/AbBOT-api#10]
Hi

I think it better to turn `debug=True` to `debug=False`
because `debug=True` is better in a development environment,
so for production env. it is better to set it to False [here](https://github.com/ramblingjordan/AbBOT-api/blob/3ededc616f0a16b648870682db200cd42b8e3baa/api/api.py#L37).

If I can do that, please assign me an issue.
Thanks.

**Comment by andria-dev** [comment]
We should probably use an environment variable and default to False so that the developers can still get debug logs easily. Normally I would suggest adding a `-v` but I think that's not possible since this is running in Docker (I'm not super familiar with Docker).

**Comment by TawfikYasser** [comment]
@andria-dev thanks for your explanation.
