### ISSUE TITLE
Non-Texas ZIP codes being returned

### ISSUE THREAD

**Issue by coolgeek6667** [ramblingjordan/AbBOT-api#2]
The data being returned for `text-4` rarely is a valid Texas zip code, The current sample return in the readme is just such a case.

**Comment by coolgeek6667** [comment]
The code already has a list of ZIP codes, but when it comes to assigning the value we are just using a random number.
I'll plan on using faker to populate that field with a valid TX zip code.

**Comment by ticet11** [comment]
I implemented some code for the AbBOT-python that should fix this. @andria-dev suggested it would be more useful here.
